# Test HTTP request
### use with: REST Client extension

@apiurl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyMywidXNlcm5hbWUiOiJ0ZXN0aXVzZXIiLCJlbWFpbCI6InRlc3RpQGV4YW1wbGUuY29tIiwiY3JlYXRlZF9hdCI6IjIwMjYtMDItMjZUMTQ6MTA6MTguMDAwWiIsInVzZXJfbGV2ZWwiOiJyZWd1bGFyIiwiaWF0IjoxNzcyMTE1MDU1LCJleHAiOjE3NzIyMDE0NTV9.hJMFhfGP8U1RoW7Oe2vT7bBRqY_SQcSh-0QmxHEj430

### GET all items
GET {{apiurl}}/items

### GET item with id 1
GET {{apiurl}}/items/1

### Add new item
POST {{apiurl}}/items
Content-Type: application/json

{"name": "Mandariini", "weight": 86}

### Delete item with id 2
DELETE {{apiurl}}/items/2

### Update item with id 1
PUT {{apiurl}}/items/1
Content-Type: application/json

{"name": "updated Omena"}

###################
### users endpoints

### GET all users (with token)
GET {{apiurl}}/users
Authorization: Bearer {{token}}

### Get user by id:
GET {{apiurl}}/users/3

### Register new user
POST {{apiurl}}/users
Content-Type: application/json

{
  "username": "testiuser",
  "password": "testisalis",
  "email": "testi@example.com"
}

### Register new user Fail (missing email)
POST {{apiurl}}/users
Content-Type: application/json

{
  "username": "donald",
  "password": "duck",
}

### User login
POST {{apiurl}}/users/login
Content-Type: application/json

{
  "username": "testiuser",
  "password": "testisalis"
}

### Get user info by token
GET {{apiurl}}/users/me
Authorization: Bearer {{token}}

### Get user by id 1
GET {{apiurl}}/user/1

### Put user by id 1
PUT {{apiurl}}/user/1
Content-Type: application/json

{
  "username": "donald",
  "email": "donald.duck@example.com"
}

### Delete user by id 1
DELETE {{apiurl}}/user/11

### Diary entry endpoints

### Get all entries (by user id in token)
GET {{apiurl}}/entries
Authorization: Bearer {{token}}

### Get entries using id
GET {{apiurl}}entries/6

### Delete entry by id
DELETE {{apiurl}}/entries/6
Authorization: Bearer {{token}}

### Post new entry
POST {{apiurl}}/entries
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "entry_date": "2026-02-05",
  "mood": "really happy",
  "weight": 72,
  "sleep_hours": 7,
  "notes": "normipäivä"
}
