# Test HTTP request
### use with: REST Client extension

###Get all items
GET http://localhost:3000/items

### Add new item
POST http://localhost:3000/items
Content-Type: application/json

{"name": "Mandariini", "weight": 86}

### elete item with id
DELETE http://localhost:3000/items/2

### update item with id
PUT http://localhost:3000/items/1
Content-Type: application/json

{"Name": "updated Omena"}
